
<script>
export default {

}
</script>

<template>
    <div class="loadingio-spinner-ellipsis-2c2wimbj7gr"><div class="ldio-lgqe77bba3d">
      <div></div><div></div><div></div><div></div><div></div>
      </div></div>
  </template>
  

<style scoped>
 @keyframes ldio-lgqe77bba3d {
       0% { transform: translate(12px,80px) scale(0) }
      25% { transform: translate(12px,80px) scale(0) }
      50% { transform: translate(12px,80px) scale(1) }
      75% { transform: translate(80px,80px) scale(1)}
     100% { transform: translate(148px,80px) scale(1) }
    }
    @keyframes ldio-lgqe77bba3d-r {
       0% { transform: translate(148px,80px) scale(1)}
     100% { transform: translate(148px,80px) scale(0)}
    }
    @keyframes ldio-lgqe77bba3d-c {
       0% { background: #e15b64 }
      25% { background: #abbd81 }
      50% { background: #f8b26a }
      75% { background: #f47e60 }
     100% { background: #e15b64 }
    }
    .ldio-lgqe77bba3d div {
      position: absolute;
      width: 30px;
      height: 30px;
      border-radius: 50%;
      transform: translate(80px,80px) scale(1);
      background: #e15b64;
      animation: ldio-lgqe77bba3d 1s infinite cubic-bezier(0,0.5,0.5,1);
    }
    .ldio-lgqe77bba3d div:nth-child(1) {
      background: #f47e60;
      transform: translate(148px,80px) scale(1);
      animation: ldio-lgqe77bba3d-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-lgqe77bba3d-c 1s infinite step-start;
    }.ldio-lgqe77bba3d div:nth-child(2) {
      animation-delay: -0.25s;
      background: #e15b64;
    }.ldio-lgqe77bba3d div:nth-child(3) {
      animation-delay: -0.5s;
      background: #f47e60;
    }.ldio-lgqe77bba3d div:nth-child(4) {
      animation-delay: -0.75s;
      background: #f8b26a;
    }.ldio-lgqe77bba3d div:nth-child(5) {
      animation-delay: -1s;
      background: #abbd81;
    }
    .loadingio-spinner-ellipsis-2c2wimbj7gr {
      width: 200px;
      height: 200px;
      display: inline-block;
      overflow: hidden;
      background: #ffffff;
    }
    .ldio-lgqe77bba3d {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-lgqe77bba3d div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>
